version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: ApiGateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
